{
 "title": "NestJS Logs",
 "tags": [
  "logs",
  "loki",
  "nestjs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({application=\"nestjs-app\"} [$__range]))"
    }
   ]
  },
  {
   "title": "4xx Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({application=\"nestjs-app\"} |~ \"\\\"statusCode\\\":4[0-9]{2}\" [$__range]))"
    }
   ]
  },
  {
   "title": "5xx Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({application=\"nestjs-app\"} |~ \"\\\"statusCode\\\":5[0-9]{2}\" [$__range]))"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({application=\"nestjs-app\"} |= \"\\\"level\\\":40\" [$__range]))"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{application=\"nestjs-app\"}"
    }
   ]
  }
 ]
}