export const ERROR_TYPES = {
    // Validation errors
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    CODE_VALIDATION_ERROR: 'CODE_VALIDATION_ERROR',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    CORS: 'CORS_ERROR',

    // Auth errors
    AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
    AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
    AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
    AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
    AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
    AUTH_REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
    AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

    // User errors
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_VALIDATION: 'USER_VALIDATION',
    USERNAME_ALREADY_SET: 'USERNAME_ALREADY_SET',
    USERNAME_CONFLICT: 'USERNAME_CONFLICT',
    USER_MAX_SKILLS_REACHED: 'USER_MAX_SKILLS_REACHED',
    USER_SKILL_NOT_FOUND: 'USER_SKILL_NOT_FOUND',
    USER_MAX_PORTFOLIO_ITEMS_REACHED: 'USER_MAX_PORTFOLIO_ITEMS_REACHED',
    USER_PORTFOLIO_ITEM_NOT_FOUND: 'USER_PORTFOLIO_ITEM_NOT_FOUND',

    // Upload errors
    UPLOAD_FILE_TOO_LARGE: 'UPLOAD_FILE_TOO_LARGE',
    UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
    UPLOAD_INVALID_FILE: 'UPLOAD_INVALID_FILE',
    UPLOAD_DELETE_FAILED: 'UPLOAD_DELETE_FAILED',
    UPLOAD_FILE_NOT_FOUND: 'UPLOAD_FILE_NOT_FOUND',
    UPLOAD_FAILED: 'UPLOAD_FAILED',
    IMAGE_PROCESSING_FAILED: 'IMAGE_PROCESSING_FAILED',
    IMAGE_INVALID: 'IMAGE_INVALID',

    // Email errors
    EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

    // Rate limiting errors
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

    // Generic errors
    GENERIC: 'GENERIC_ERROR',
    BAD_REQUEST: 'BAD_REQUEST_ERROR',
    THROTTLE: 'THROTTLE_ERROR'
}

export const ERROR_CODES = {
    // Validation error codes (400, 422)
    BAD_REQUEST: '400000',
    USER_VALIDATION: '400001',
    USERNAME_ALREADY_SET: '400200',
    CODE_VALIDATION_ERROR: '400100',
    SESSION_EXPIRED: '400101',
    VALIDATION_ERROR: '422000',

    // Auth error codes (401)
    AUTH_UNAUTHORIZED: '401000',
    AUTH_INVALID_CREDENTIALS: '401001',
    AUTH_USER_NOT_FOUND: '401002',
    AUTH_TOKEN_MISSING: '401003',
    AUTH_TOKEN_EXPIRED: '401004',
    AUTH_TOKEN_INVALID: '401005',
    AUTH_TOKEN_REVOKED: '401006',
    AUTH_LOGIN_FAILED: '401007',
    AUTH_REFRESH_FAILED: '401008',

    // Forbidden error codes (403)
    AUTH_EMAIL_NOT_VERIFIED: '403002',
    AUTH_ACCOUNT_DISABLED: '403003',
    AUTH_FORBIDDEN: '403004',
    CORS_ERROR: '403001',

    // Not found error codes (404)
    USER_NOT_FOUND: '404001',
    USER_SKILL_NOT_FOUND: '404003',
    USER_PORTFOLIO_ITEM_NOT_FOUND: '404004',

    // Conflict error codes (409)
    AUTH_EMAIL_EXISTS: '409001',
    USERNAME_CONFLICT: '409200',
    USER_MAX_SKILLS_REACHED: '409201',
    USER_MAX_PORTFOLIO_ITEMS_REACHED: '409202',

    // Upload error codes (400, 404, 413, 415, 422, 500)
    UPLOAD_INVALID_FILE: '400002',
    UPLOAD_FILE_NOT_FOUND: '404002',
    UPLOAD_FILE_TOO_LARGE: '413001',
    UPLOAD_INVALID_TYPE: '415001',
    IMAGE_PROCESSING_FAILED: '422001',
    IMAGE_INVALID: '422002',
    UPLOAD_DELETE_FAILED: '500002',
    UPLOAD_FAILED: '500003',

    // Rate limiting error codes (429)
    RATE_LIMIT_EXCEEDED: '429001',

    // Server error codes (500)
    GENERIC: '500000',
    EMAIL_SEND_FAILED: '500001'
}
