export const ERROR_TYPES = {
    // Validation
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    CODE_VALIDATION_ERROR: 'CODE_VALIDATION_ERROR',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    CORS: 'CORS_ERROR',

    // Auth
    AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
    AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
    AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
    AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
    AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
    AUTH_REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
    AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

    // User
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_VALIDATION: 'USER_VALIDATION',
    USERNAME_ALREADY_SET: 'USERNAME_ALREADY_SET',
    USERNAME_CONFLICT: 'USERNAME_CONFLICT',
    USER_MAX_SKILLS_REACHED: 'USER_MAX_SKILLS_REACHED',
    USER_SKILL_NOT_FOUND: 'USER_SKILL_NOT_FOUND',
    USER_MAX_PORTFOLIO_ITEMS_REACHED: 'USER_MAX_PORTFOLIO_ITEMS_REACHED',
    USER_PORTFOLIO_ITEM_NOT_FOUND: 'USER_PORTFOLIO_ITEM_NOT_FOUND',

    // Categories
    CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
    CATEGORY_NAME_CONFLICT: 'CATEGORY_NAME_CONFLICT',
    CATEGORY_INVALID_ICON: 'CATEGORY_INVALID_ICON',
    CATEGORY_HAS_GIGS: 'CATEGORY_HAS_GIGS',
    CATEGORY_INVALID_REASSIGN_TARGET: 'CATEGORY_INVALID_REASSIGN_TARGET',

    // Gigs
    GIG_NOT_FOUND: 'GIG_NOT_FOUND',
    GIG_INVALID_STATUS_TRANSITION: 'GIG_INVALID_STATUS_TRANSITION',
    GIG_IMAGE_CAP_REACHED: 'GIG_IMAGE_CAP_REACHED',
    GIG_BULLET_CAP_REACHED: 'GIG_BULLET_CAP_REACHED',
    GIG_FAQ_CAP_REACHED: 'GIG_FAQ_CAP_REACHED',
    GIG_IMAGE_NOT_OWNED: 'GIG_IMAGE_NOT_OWNED',
    GIG_ADMIN_CANNOT_CREATE: 'GIG_ADMIN_CANNOT_CREATE',
    GIG_CATEGORY_NOT_FOUND: 'GIG_CATEGORY_NOT_FOUND',
    GIG_LOCKED_FOR_REVIEW: 'GIG_LOCKED_FOR_REVIEW',
    GIG_NOT_PENDING: 'GIG_NOT_PENDING',

    // Messaging
    MESSAGING_CANNOT_MESSAGE_SELF: 'MESSAGING_CANNOT_MESSAGE_SELF',
    MESSAGING_NOT_A_PARTICIPANT: 'MESSAGING_NOT_A_PARTICIPANT',
    MESSAGING_EMPTY_MESSAGE: 'MESSAGING_EMPTY_MESSAGE',
    MESSAGING_TOO_MANY_ATTACHMENTS: 'MESSAGING_TOO_MANY_ATTACHMENTS',
    MESSAGING_UNSUPPORTED_ATTACHMENT_TYPE: 'MESSAGING_UNSUPPORTED_ATTACHMENT_TYPE',
    MESSAGING_ATTACHMENT_TOO_LARGE: 'MESSAGING_ATTACHMENT_TOO_LARGE',
    MESSAGING_THREAD_NOT_FOUND: 'MESSAGING_THREAD_NOT_FOUND',

    // Orders
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    ORDERS_NOT_A_PARTICIPANT: 'ORDERS_NOT_A_PARTICIPANT',
    ORDERS_INVALID_TRANSITION: 'ORDERS_INVALID_TRANSITION',
    ORDERS_INSUFFICIENT_WALLET_BALANCE: 'ORDERS_INSUFFICIENT_WALLET_BALANCE',
    ORDERS_SELLER_CANNOT_ORDER_OWN_GIG: 'ORDERS_SELLER_CANNOT_ORDER_OWN_GIG',
    ORDERS_PENDING_EXTENSION_EXISTS: 'ORDERS_PENDING_EXTENSION_EXISTS',
    ORDERS_PENDING_CANCELLATION_EXISTS: 'ORDERS_PENDING_CANCELLATION_EXISTS',
    ORDERS_DELIVERY_NOTE_TOO_SHORT: 'ORDERS_DELIVERY_NOTE_TOO_SHORT',
    ORDERS_DECLINE_NOTE_TOO_SHORT: 'ORDERS_DECLINE_NOTE_TOO_SHORT',
    ORDERS_GIG_NOT_PURCHASABLE: 'ORDERS_GIG_NOT_PURCHASABLE',
    ORDERS_TOO_MANY_DELIVERY_FILES: 'ORDERS_TOO_MANY_DELIVERY_FILES',
    ORDERS_UNSUPPORTED_DELIVERY_FILE_TYPE: 'ORDERS_UNSUPPORTED_DELIVERY_FILE_TYPE',
    ORDERS_DELIVERY_FILE_TOO_LARGE: 'ORDERS_DELIVERY_FILE_TOO_LARGE',

    // Reviews
    REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
    REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
    REVIEW_ORDER_NOT_COMPLETED: 'REVIEW_ORDER_NOT_COMPLETED',
    REVIEW_NOT_THE_BUYER: 'REVIEW_NOT_THE_BUYER',
    REVIEW_REPLY_ALREADY_EXISTS: 'REVIEW_REPLY_ALREADY_EXISTS',
    REVIEW_GIG_NOT_ACTIVE: 'REVIEW_GIG_NOT_ACTIVE',
    REVIEW_NOT_THE_SELLER: 'REVIEW_NOT_THE_SELLER',

    // Upload
    UPLOAD_FILE_TOO_LARGE: 'UPLOAD_FILE_TOO_LARGE',
    UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
    UPLOAD_INVALID_FILE: 'UPLOAD_INVALID_FILE',
    UPLOAD_DELETE_FAILED: 'UPLOAD_DELETE_FAILED',
    UPLOAD_FILE_NOT_FOUND: 'UPLOAD_FILE_NOT_FOUND',
    UPLOAD_FAILED: 'UPLOAD_FAILED',
    IMAGE_PROCESSING_FAILED: 'IMAGE_PROCESSING_FAILED',
    IMAGE_INVALID: 'IMAGE_INVALID',

    // Email
    EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

    // Rate limiting
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

    // Generic
    GENERIC: 'GENERIC_ERROR',
    BAD_REQUEST: 'BAD_REQUEST_ERROR',
    THROTTLE: 'THROTTLE_ERROR'
}

export const ERROR_CODES = {
    // 400 / 422
    BAD_REQUEST: '400000',
    USER_VALIDATION: '400001',
    USERNAME_ALREADY_SET: '400200',
    CODE_VALIDATION_ERROR: '400100',
    SESSION_EXPIRED: '400101',
    VALIDATION_ERROR: '422000',

    // 401
    AUTH_UNAUTHORIZED: '401000',
    AUTH_INVALID_CREDENTIALS: '401001',
    AUTH_USER_NOT_FOUND: '401002',
    AUTH_TOKEN_MISSING: '401003',
    AUTH_TOKEN_EXPIRED: '401004',
    AUTH_TOKEN_INVALID: '401005',
    AUTH_TOKEN_REVOKED: '401006',
    AUTH_LOGIN_FAILED: '401007',
    AUTH_REFRESH_FAILED: '401008',

    // 403
    AUTH_EMAIL_NOT_VERIFIED: '403002',
    AUTH_ACCOUNT_DISABLED: '403003',
    AUTH_FORBIDDEN: '403004',
    CORS_ERROR: '403001',

    // 404
    USER_NOT_FOUND: '404001',
    USER_SKILL_NOT_FOUND: '404003',
    USER_PORTFOLIO_ITEM_NOT_FOUND: '404004',
    CATEGORY_NOT_FOUND: '404005',
    GIG_NOT_FOUND: '404006',
    GIG_IMAGE_NOT_OWNED: '404007',
    GIG_CATEGORY_NOT_FOUND: '404008',
    MESSAGING_THREAD_NOT_FOUND: '404009',

    // 409
    AUTH_EMAIL_EXISTS: '409001',
    USERNAME_CONFLICT: '409200',
    USER_MAX_SKILLS_REACHED: '409201',
    USER_MAX_PORTFOLIO_ITEMS_REACHED: '409202',
    CATEGORY_NAME_CONFLICT: '409300',
    CATEGORY_HAS_GIGS: '409301',
    GIG_INVALID_STATUS_TRANSITION: '409400',
    GIG_IMAGE_CAP_REACHED: '409401',
    GIG_BULLET_CAP_REACHED: '409402',
    GIG_FAQ_CAP_REACHED: '409403',
    GIG_LOCKED_FOR_REVIEW: '409404',
    GIG_NOT_PENDING: '409405',
    GIG_ADMIN_CANNOT_CREATE: '403100',

    // Messaging
    MESSAGING_CANNOT_MESSAGE_SELF: '400400',
    MESSAGING_NOT_A_PARTICIPANT: '403400',
    MESSAGING_EMPTY_MESSAGE: '400401',
    MESSAGING_TOO_MANY_ATTACHMENTS: '422400',
    MESSAGING_UNSUPPORTED_ATTACHMENT_TYPE: '415400',
    MESSAGING_ATTACHMENT_TOO_LARGE: '413400',

    // Orders
    ORDER_NOT_FOUND: '404500',
    ORDERS_NOT_A_PARTICIPANT: '403500',
    ORDERS_INVALID_TRANSITION: '409500',
    ORDERS_INSUFFICIENT_WALLET_BALANCE: '422500',
    ORDERS_SELLER_CANNOT_ORDER_OWN_GIG: '400500',
    ORDERS_PENDING_EXTENSION_EXISTS: '409501',
    ORDERS_PENDING_CANCELLATION_EXISTS: '409502',
    ORDERS_DELIVERY_NOTE_TOO_SHORT: '400501',
    ORDERS_DECLINE_NOTE_TOO_SHORT: '400502',
    ORDERS_GIG_NOT_PURCHASABLE: '409503',
    ORDERS_TOO_MANY_DELIVERY_FILES: '422501',
    ORDERS_UNSUPPORTED_DELIVERY_FILE_TYPE: '415500',
    ORDERS_DELIVERY_FILE_TOO_LARGE: '413500',

    // Reviews
    REVIEW_NOT_FOUND: '404600',
    REVIEW_NOT_THE_BUYER: '403600',
    REVIEW_NOT_THE_SELLER: '403601',
    REVIEW_ALREADY_EXISTS: '409600',
    REVIEW_REPLY_ALREADY_EXISTS: '409601',
    REVIEW_GIG_NOT_ACTIVE: '409602',
    REVIEW_ORDER_NOT_COMPLETED: '409603',

    // Category validation
    CATEGORY_INVALID_ICON: '400300',
    CATEGORY_INVALID_REASSIGN_TARGET: '400301',

    // Upload
    UPLOAD_INVALID_FILE: '400002',
    UPLOAD_FILE_NOT_FOUND: '404002',
    UPLOAD_FILE_TOO_LARGE: '413001',
    UPLOAD_INVALID_TYPE: '415001',
    IMAGE_PROCESSING_FAILED: '422001',
    IMAGE_INVALID: '422002',
    UPLOAD_DELETE_FAILED: '500002',
    UPLOAD_FAILED: '500003',

    // 429
    RATE_LIMIT_EXCEEDED: '429001',

    // 500
    GENERIC: '500000',
    EMAIL_SEND_FAILED: '500001'
}
