export const RESPONSE_CODES = {
    // Success codes
    SUCCESS: '200000',

    // Auth codes
    AUTH_LOGIN_SUCCESS: '200100',
    AUTH_REGISTER_SUCCESS: '200101',
    AUTH_REFRESH_SUCCESS: '200102',
    VERIFY_CODE_SUCCESS: '200103',
    AUTH_LOGOUT_SUCCESS: '200104',
    AUTH_TOKEN_REFRESHED: '200105',

    // User codes
    USER_FETCH_SUCCESS: '200200',
    USER_FETCHED: '200200',
    USER_UPDATE_SUCCESS: '200201',
    USER_DELETE_SUCCESS: '200202',

    // Category codes (Feature 03)
    CATEGORIES_FETCH_SUCCESS: '200210',
    CATEGORY_CREATE_SUCCESS: '200211',
    CATEGORY_UPDATE_SUCCESS: '200212',
    CATEGORY_DELETE_SUCCESS: '200213',

    // Upload codes
    UPLOAD_FILE_SUCCESS: '200300',

    // Email codes
    EMAIL_SEND_SUCCESS: '200400',

    // Health codes
    HEALTH_CHECK_SUCCESS: '200500',

    // Cache codes
    CACHE_OPERATION_SUCCESS: '200600'
}

export const RESPONSE_TYPES = {
    // Success types
    SUCCESS: 'SUCCESS',

    // Auth types
    AUTH_LOGIN: 'AUTH_LOGIN_SUCCESS',
    AUTH_REGISTER: 'AUTH_REGISTER_SUCCESS',
    AUTH_REFRESH: 'AUTH_REFRESH_SUCCESS',
    VERIFY_CODE: 'VERIFY_CODE_SUCCESS',
    AUTH_LOGOUT: 'AUTH_LOGOUT_SUCCESS',
    // User types
    USER_FETCH: 'USER_FETCH_SUCCESS',
    USER_UPDATE: 'USER_UPDATE_SUCCESS',
    USER_DELETE: 'USER_DELETE_SUCCESS',

    // Category types (Feature 03)
    CATEGORIES_FETCH: 'CATEGORIES_FETCH_SUCCESS',
    CATEGORY_CREATE: 'CATEGORY_CREATE_SUCCESS',
    CATEGORY_UPDATE: 'CATEGORY_UPDATE_SUCCESS',
    CATEGORY_DELETE: 'CATEGORY_DELETE_SUCCESS',

    // Upload types
    UPLOAD_FILE: 'UPLOAD_FILE_SUCCESS',

    // Email types
    EMAIL_SEND: 'EMAIL_SEND_SUCCESS',

    // Health types
    HEALTH_CHECK: 'HEALTH_CHECK_SUCCESS',

    // Cache types
    CACHE_OPERATION: 'CACHE_OPERATION_SUCCESS'
}
