export const RESPONSE_CODES = {
    // Success
    SUCCESS: '200000',

    // Auth
    AUTH_LOGIN_SUCCESS: '200100',
    AUTH_REGISTER_SUCCESS: '200101',
    AUTH_REFRESH_SUCCESS: '200102',
    VERIFY_CODE_SUCCESS: '200103',
    AUTH_LOGOUT_SUCCESS: '200104',
    AUTH_TOKEN_REFRESHED: '200105',

    // User
    USER_FETCH_SUCCESS: '200200',
    USER_FETCHED: '200200',
    USER_UPDATE_SUCCESS: '200201',
    USER_DELETE_SUCCESS: '200202',

    // Categories
    CATEGORIES_FETCH_SUCCESS: '200210',
    CATEGORY_CREATE_SUCCESS: '200211',
    CATEGORY_UPDATE_SUCCESS: '200212',
    CATEGORY_DELETE_SUCCESS: '200213',

    // Gigs
    GIGS_FETCH_SUCCESS: '200220',
    GIG_FETCH_SUCCESS: '200221',
    GIG_CREATE_SUCCESS: '200222',
    GIG_UPDATE_SUCCESS: '200223',
    GIG_PAUSE_SUCCESS: '200224',
    GIG_RESUME_SUCCESS: '200225',
    GIG_DELETE_SUCCESS: '200226',
    GIG_IMAGE_UPLOAD_SUCCESS: '200227',
    GIG_IMAGE_DELETE_SUCCESS: '200228',
    GIG_IMAGES_REORDER_SUCCESS: '200229',

    // Admin Gig Queue
    ADMIN_GIG_QUEUE_FETCH_SUCCESS: '200230',
    ADMIN_GIG_FETCH_SUCCESS: '200231',
    ADMIN_GIG_APPROVE_SUCCESS: '200232',
    ADMIN_GIG_REJECT_SUCCESS: '200233',

    // Public Gigs + Wishlist
    PUBLIC_GIGS_BROWSE_SUCCESS: '200240',
    PUBLIC_GIG_FETCH_SUCCESS: '200241',
    WISHLIST_SAVE_SUCCESS: '200242',
    WISHLIST_UNSAVE_SUCCESS: '200243',
    WISHLIST_FETCH_SUCCESS: '200244',

    // Gig analytics (views + Manage Gig performance stats)
    GIG_VIEW_RECORD_SUCCESS: '200245',
    GIG_STATS_FETCH_SUCCESS: '200246',

    // Wallet + Withdrawals
    WALLET_FETCH_SUCCESS: '200250',
    WALLET_TRANSACTIONS_FETCH_SUCCESS: '200251',
    WALLET_DEPOSIT_SUCCESS: '200252',
    WALLET_WITHDRAW_SUCCESS: '200253',
    WALLET_BANK_ACCOUNT_UPDATE_SUCCESS: '200254',
    ADMIN_WITHDRAWALS_LIST_SUCCESS: '200255',
    ADMIN_WITHDRAWAL_FETCH_SUCCESS: '200256',
    ADMIN_WITHDRAWAL_APPROVE_SUCCESS: '200257',
    ADMIN_WITHDRAWAL_REJECT_SUCCESS: '200258',

    // Messaging
    MESSAGING_THREAD_CREATE_SUCCESS: '200260',
    MESSAGING_CONVERSATIONS_LIST_SUCCESS: '200261',
    MESSAGING_MESSAGES_LIST_SUCCESS: '200262',
    MESSAGING_MESSAGE_SEND_SUCCESS: '200263',
    MESSAGING_ATTACHMENT_UPLOAD_SUCCESS: '200264',
    MESSAGING_THREAD_READ_SUCCESS: '200265',
    MESSAGING_UNREAD_COUNT_SUCCESS: '200266',
    MESSAGING_FILES_LIST_SUCCESS: '200267',
    MESSAGING_ATTACHMENT_RESOLVE_SUCCESS: '200268',
    MESSAGING_RESPONSE_TIME_SUCCESS: '200269',

    // Orders
    ORDERS_PLACE_SUCCESS: '200270',
    ORDERS_FETCH_SUCCESS: '200271',
    ORDERS_LIST_SUCCESS: '200272',
    ORDERS_EVENTS_FETCH_SUCCESS: '200273',
    ORDERS_ACTION_COUNTS_SUCCESS: '200274',
    ORDERS_ACCEPT_SUCCESS: '200275',
    ORDERS_DECLINE_SUCCESS: '200276',
    ORDERS_DELIVER_SUCCESS: '200277',
    ORDERS_DELIVERY_FILE_STAGE_SUCCESS: '200278',
    ORDERS_DELIVERY_FILE_RESOLVE_SUCCESS: '200279',
    ORDERS_ACCEPT_DELIVERY_SUCCESS: '200280',
    ORDERS_DELIVERY_UPDATE_SUCCESS: '200281',
    ORDERS_DELIVERIES_LIST_SUCCESS: '200282',
    ORDERS_EXTENSION_REQUEST_SUCCESS: '200283',
    ORDERS_EXTENSION_DECIDE_SUCCESS: '200284',
    ORDERS_CANCELLATION_REQUEST_SUCCESS: '200285',
    ORDERS_CANCELLATION_DECIDE_SUCCESS: '200286',

    // Reviews
    REVIEW_SUBMIT_SUCCESS: '200290',
    REVIEW_REPLY_SUCCESS: '200291',
    REVIEWS_LIST_SUCCESS: '200292',
    REVIEW_SUMMARY_SUCCESS: '200293',
    REVIEWS_MANAGE_LIST_SUCCESS: '200294',

    // Disputes
    DISPUTE_FILE_SUCCESS: '200310',
    DISPUTE_RESPOND_SUCCESS: '200311',
    DISPUTE_ADD_EVIDENCE_SUCCESS: '200312',
    DISPUTE_EVIDENCE_UPLOAD_SUCCESS: '200313',
    DISPUTE_EVIDENCE_URL_SUCCESS: '200314',
    ADMIN_DISPUTES_LIST_SUCCESS: '200315',
    ADMIN_DISPUTE_FETCH_SUCCESS: '200316',
    ADMIN_DISPUTE_VERDICT_SUCCESS: '200317',

    // Admin dashboard + remaining pages
    ADMIN_ACTIVITY_LIST_SUCCESS: '200320',
    ADMIN_USERS_LIST_SUCCESS: '200321',
    ADMIN_USER_DETAIL_SUCCESS: '200322',
    ADMIN_USER_ENDORSE_SUCCESS: '200323',
    ADMIN_USER_REVOKE_SUCCESS: '200324',
    ADMIN_USER_NOTE_SUCCESS: '200325',
    ADMIN_DASHBOARD_SUCCESS: '200326',
    ADMIN_REPORT_EXPORTS_LIST_SUCCESS: '200327',

    // Notifications (F15)
    NOTIFICATIONS_LIST_SUCCESS: '200330',
    NOTIFICATIONS_RECENT_SUCCESS: '200331',
    NOTIFICATIONS_UNREAD_COUNT_SUCCESS: '200332',
    NOTIFICATION_READ_SUCCESS: '200333',
    NOTIFICATIONS_READ_ALL_SUCCESS: '200334',

    // User Dashboard (F16)
    DASHBOARD_SELLER_SUCCESS: '200335',
    DASHBOARD_BUYER_SUCCESS: '200336',

    // Upload
    UPLOAD_FILE_SUCCESS: '200300',

    // Email
    EMAIL_SEND_SUCCESS: '200400',

    // Health
    HEALTH_CHECK_SUCCESS: '200500',

    // Cache
    CACHE_OPERATION_SUCCESS: '200600'
}

export const RESPONSE_TYPES = {
    // Success
    SUCCESS: 'SUCCESS',

    // Auth
    AUTH_LOGIN: 'AUTH_LOGIN_SUCCESS',
    AUTH_REGISTER: 'AUTH_REGISTER_SUCCESS',
    AUTH_REFRESH: 'AUTH_REFRESH_SUCCESS',
    VERIFY_CODE: 'VERIFY_CODE_SUCCESS',
    AUTH_LOGOUT: 'AUTH_LOGOUT_SUCCESS',

    // User
    USER_FETCH: 'USER_FETCH_SUCCESS',
    USER_UPDATE: 'USER_UPDATE_SUCCESS',
    USER_DELETE: 'USER_DELETE_SUCCESS',

    // Categories
    CATEGORIES_FETCH: 'CATEGORIES_FETCH_SUCCESS',
    CATEGORY_CREATE: 'CATEGORY_CREATE_SUCCESS',
    CATEGORY_UPDATE: 'CATEGORY_UPDATE_SUCCESS',
    CATEGORY_DELETE: 'CATEGORY_DELETE_SUCCESS',

    // Gigs
    GIGS_FETCH: 'GIGS_FETCH_SUCCESS',
    GIG_FETCH: 'GIG_FETCH_SUCCESS',
    GIG_CREATE: 'GIG_CREATE_SUCCESS',
    GIG_UPDATE: 'GIG_UPDATE_SUCCESS',
    GIG_PAUSE: 'GIG_PAUSE_SUCCESS',
    GIG_RESUME: 'GIG_RESUME_SUCCESS',
    GIG_DELETE: 'GIG_DELETE_SUCCESS',
    GIG_IMAGE_UPLOAD: 'GIG_IMAGE_UPLOAD_SUCCESS',
    GIG_IMAGE_DELETE: 'GIG_IMAGE_DELETE_SUCCESS',
    GIG_IMAGES_REORDER: 'GIG_IMAGES_REORDER_SUCCESS',

    // Admin Gig Queue
    ADMIN_GIG_QUEUE_FETCH: 'ADMIN_GIG_QUEUE_FETCH_SUCCESS',
    ADMIN_GIG_FETCH: 'ADMIN_GIG_FETCH_SUCCESS',
    ADMIN_GIG_APPROVE: 'ADMIN_GIG_APPROVE_SUCCESS',
    ADMIN_GIG_REJECT: 'ADMIN_GIG_REJECT_SUCCESS',

    // Public Gigs + Wishlist
    PUBLIC_GIGS_BROWSE: 'PUBLIC_GIGS_BROWSE_SUCCESS',
    PUBLIC_GIG_FETCH: 'PUBLIC_GIG_FETCH_SUCCESS',
    WISHLIST_SAVE: 'WISHLIST_SAVE_SUCCESS',
    WISHLIST_UNSAVE: 'WISHLIST_UNSAVE_SUCCESS',
    WISHLIST_FETCH: 'WISHLIST_FETCH_SUCCESS',

    // Gig analytics (views + Manage Gig performance stats)
    GIG_VIEW_RECORD: 'GIG_VIEW_RECORD_SUCCESS',
    GIG_STATS_FETCH: 'GIG_STATS_FETCH_SUCCESS',

    // Wallet + Withdrawals
    WALLET_FETCH: 'WALLET_FETCH_SUCCESS',
    WALLET_TRANSACTIONS_FETCH: 'WALLET_TRANSACTIONS_FETCH_SUCCESS',
    WALLET_DEPOSIT: 'WALLET_DEPOSIT_SUCCESS',
    WALLET_WITHDRAW: 'WALLET_WITHDRAW_SUCCESS',
    WALLET_BANK_ACCOUNT_UPDATE: 'WALLET_BANK_ACCOUNT_UPDATE_SUCCESS',
    ADMIN_WITHDRAWALS_LIST: 'ADMIN_WITHDRAWALS_LIST_SUCCESS',
    ADMIN_WITHDRAWAL_FETCH: 'ADMIN_WITHDRAWAL_FETCH_SUCCESS',
    ADMIN_WITHDRAWAL_APPROVE: 'ADMIN_WITHDRAWAL_APPROVE_SUCCESS',
    ADMIN_WITHDRAWAL_REJECT: 'ADMIN_WITHDRAWAL_REJECT_SUCCESS',

    // Messaging
    MESSAGING_THREAD_CREATE: 'MESSAGING_THREAD_CREATE_SUCCESS',
    MESSAGING_CONVERSATIONS_LIST: 'MESSAGING_CONVERSATIONS_LIST_SUCCESS',
    MESSAGING_MESSAGES_LIST: 'MESSAGING_MESSAGES_LIST_SUCCESS',
    MESSAGING_MESSAGE_SEND: 'MESSAGING_MESSAGE_SEND_SUCCESS',
    MESSAGING_ATTACHMENT_UPLOAD: 'MESSAGING_ATTACHMENT_UPLOAD_SUCCESS',
    MESSAGING_THREAD_READ: 'MESSAGING_THREAD_READ_SUCCESS',
    MESSAGING_UNREAD_COUNT: 'MESSAGING_UNREAD_COUNT_SUCCESS',
    MESSAGING_FILES_LIST: 'MESSAGING_FILES_LIST_SUCCESS',
    MESSAGING_ATTACHMENT_RESOLVE: 'MESSAGING_ATTACHMENT_RESOLVE_SUCCESS',
    MESSAGING_RESPONSE_TIME: 'MESSAGING_RESPONSE_TIME_SUCCESS',

    // Orders
    ORDERS_PLACE: 'ORDERS_PLACE_SUCCESS',
    ORDERS_FETCH: 'ORDERS_FETCH_SUCCESS',
    ORDERS_LIST: 'ORDERS_LIST_SUCCESS',
    ORDERS_EVENTS_FETCH: 'ORDERS_EVENTS_FETCH_SUCCESS',
    ORDERS_ACTION_COUNTS: 'ORDERS_ACTION_COUNTS_SUCCESS',
    ORDERS_ACCEPT: 'ORDERS_ACCEPT_SUCCESS',
    ORDERS_DECLINE: 'ORDERS_DECLINE_SUCCESS',
    ORDERS_DELIVER: 'ORDERS_DELIVER_SUCCESS',
    ORDERS_DELIVERY_UPDATE: 'ORDERS_DELIVERY_UPDATE_SUCCESS',
    ORDERS_DELIVERIES_LIST: 'ORDERS_DELIVERIES_LIST_SUCCESS',
    ORDERS_EXTENSION_REQUEST: 'ORDERS_EXTENSION_REQUEST_SUCCESS',
    ORDERS_EXTENSION_DECIDE: 'ORDERS_EXTENSION_DECIDE_SUCCESS',
    ORDERS_CANCELLATION_REQUEST: 'ORDERS_CANCELLATION_REQUEST_SUCCESS',
    ORDERS_CANCELLATION_DECIDE: 'ORDERS_CANCELLATION_DECIDE_SUCCESS',

    // Reviews
    REVIEW_SUBMIT: 'REVIEW_SUBMIT_SUCCESS',
    REVIEW_REPLY: 'REVIEW_REPLY_SUCCESS',
    REVIEWS_LIST: 'REVIEWS_LIST_SUCCESS',
    REVIEW_SUMMARY: 'REVIEW_SUMMARY_SUCCESS',
    REVIEWS_MANAGE_LIST: 'REVIEWS_MANAGE_LIST_SUCCESS',

    // Disputes (F12)
    DISPUTE_FILE: 'DISPUTE_FILE_SUCCESS',
    DISPUTE_RESPOND: 'DISPUTE_RESPOND_SUCCESS',
    DISPUTE_ADD_EVIDENCE: 'DISPUTE_ADD_EVIDENCE_SUCCESS',
    DISPUTE_EVIDENCE_UPLOAD: 'DISPUTE_EVIDENCE_UPLOAD_SUCCESS',
    DISPUTE_EVIDENCE_URL: 'DISPUTE_EVIDENCE_URL_SUCCESS',
    ADMIN_DISPUTES_LIST: 'ADMIN_DISPUTES_LIST_SUCCESS',
    ADMIN_DISPUTE_FETCH: 'ADMIN_DISPUTE_FETCH_SUCCESS',
    ADMIN_DISPUTE_VERDICT: 'ADMIN_DISPUTE_VERDICT_SUCCESS',

    // Admin dashboard + remaining pages (F14)
    ADMIN_ACTIVITY_LIST: 'ADMIN_ACTIVITY_LIST_SUCCESS',
    ADMIN_USERS_LIST: 'ADMIN_USERS_LIST_SUCCESS',
    ADMIN_USER_DETAIL: 'ADMIN_USER_DETAIL_SUCCESS',
    ADMIN_USER_ENDORSE: 'ADMIN_USER_ENDORSE_SUCCESS',
    ADMIN_USER_REVOKE: 'ADMIN_USER_REVOKE_SUCCESS',
    ADMIN_USER_NOTE: 'ADMIN_USER_NOTE_SUCCESS',
    ADMIN_DASHBOARD: 'ADMIN_DASHBOARD_SUCCESS',
    ADMIN_REPORT_EXPORTS_LIST: 'ADMIN_REPORT_EXPORTS_LIST_SUCCESS',

    // Notifications (F15)
    NOTIFICATIONS_LIST: 'NOTIFICATIONS_LIST_SUCCESS',
    NOTIFICATIONS_RECENT: 'NOTIFICATIONS_RECENT_SUCCESS',
    NOTIFICATIONS_UNREAD_COUNT: 'NOTIFICATIONS_UNREAD_COUNT_SUCCESS',
    NOTIFICATION_READ: 'NOTIFICATION_READ_SUCCESS',
    NOTIFICATIONS_READ_ALL: 'NOTIFICATIONS_READ_ALL_SUCCESS',

    // User Dashboard (F16)
    DASHBOARD_SELLER: 'DASHBOARD_SELLER_SUCCESS',
    DASHBOARD_BUYER: 'DASHBOARD_BUYER_SUCCESS',

    ORDERS_DELIVERY_FILE_STAGE: 'ORDERS_DELIVERY_FILE_STAGE_SUCCESS',
    ORDERS_DELIVERY_FILE_RESOLVE: 'ORDERS_DELIVERY_FILE_RESOLVE_SUCCESS',
    ORDERS_ACCEPT_DELIVERY: 'ORDERS_ACCEPT_DELIVERY_SUCCESS',

    // Upload
    UPLOAD_FILE: 'UPLOAD_FILE_SUCCESS',

    // Email
    EMAIL_SEND: 'EMAIL_SEND_SUCCESS',

    // Health
    HEALTH_CHECK: 'HEALTH_CHECK_SUCCESS',

    // Cache
    CACHE_OPERATION: 'CACHE_OPERATION_SUCCESS'
}
