export const RESPONSE_CODES = {
    // Success codes
    SUCCESS: '200000',

    // Auth codes
    AUTH_LOGIN_SUCCESS: '200100',
    AUTH_REGISTER_SUCCESS: '200101',
    AUTH_REFRESH_SUCCESS: '200102',
    VERIFY_CODE_SUCCESS: '200103',
    AUTH_LOGOUT_SUCCESS: '200104',
    AUTH_TOKEN_REFRESHED: '200105',

    // User codes
    USER_FETCH_SUCCESS: '200200',
    USER_FETCHED: '200200',
    USER_UPDATE_SUCCESS: '200201',
    USER_DELETE_SUCCESS: '200202',

    // Category codes (Feature 03)
    CATEGORIES_FETCH_SUCCESS: '200210',
    CATEGORY_CREATE_SUCCESS: '200211',
    CATEGORY_UPDATE_SUCCESS: '200212',
    CATEGORY_DELETE_SUCCESS: '200213',

    // Gig codes (Feature 04)
    GIGS_FETCH_SUCCESS: '200220',
    GIG_FETCH_SUCCESS: '200221',
    GIG_CREATE_SUCCESS: '200222',
    GIG_UPDATE_SUCCESS: '200223',
    GIG_PAUSE_SUCCESS: '200224',
    GIG_RESUME_SUCCESS: '200225',
    GIG_DELETE_SUCCESS: '200226',
    GIG_IMAGE_UPLOAD_SUCCESS: '200227',
    GIG_IMAGE_DELETE_SUCCESS: '200228',
    GIG_IMAGES_REORDER_SUCCESS: '200229',

    // Admin Gig Queue codes (Feature 05)
    ADMIN_GIG_QUEUE_FETCH_SUCCESS: '200230',
    ADMIN_GIG_FETCH_SUCCESS: '200231',
    ADMIN_GIG_APPROVE_SUCCESS: '200232',
    ADMIN_GIG_REJECT_SUCCESS: '200233',

    // Public Gigs + Wishlist codes (Feature 06)
    PUBLIC_GIGS_BROWSE_SUCCESS: '200240',
    PUBLIC_GIG_FETCH_SUCCESS: '200241',
    WISHLIST_SAVE_SUCCESS: '200242',
    WISHLIST_UNSAVE_SUCCESS: '200243',
    WISHLIST_FETCH_SUCCESS: '200244',

    // Wallet + Withdrawals codes (Feature 07 + 13)
    WALLET_FETCH_SUCCESS: '200250',
    WALLET_TRANSACTIONS_FETCH_SUCCESS: '200251',
    WALLET_DEPOSIT_SUCCESS: '200252',
    WALLET_WITHDRAW_SUCCESS: '200253',
    WALLET_BANK_ACCOUNT_UPDATE_SUCCESS: '200254',
    ADMIN_WITHDRAWALS_LIST_SUCCESS: '200255',
    ADMIN_WITHDRAWAL_FETCH_SUCCESS: '200256',
    ADMIN_WITHDRAWAL_APPROVE_SUCCESS: '200257',
    ADMIN_WITHDRAWAL_REJECT_SUCCESS: '200258',

    // Messaging codes (Feature 08)
    MESSAGING_THREAD_CREATE_SUCCESS: '200260',
    MESSAGING_CONVERSATIONS_LIST_SUCCESS: '200261',
    MESSAGING_MESSAGES_LIST_SUCCESS: '200262',
    MESSAGING_MESSAGE_SEND_SUCCESS: '200263',
    MESSAGING_ATTACHMENT_UPLOAD_SUCCESS: '200264',
    MESSAGING_THREAD_READ_SUCCESS: '200265',
    MESSAGING_UNREAD_COUNT_SUCCESS: '200266',
    MESSAGING_FILES_LIST_SUCCESS: '200267',
    MESSAGING_ATTACHMENT_RESOLVE_SUCCESS: '200268',
    MESSAGING_RESPONSE_TIME_SUCCESS: '200269',

    // Upload codes
    UPLOAD_FILE_SUCCESS: '200300',

    // Email codes
    EMAIL_SEND_SUCCESS: '200400',

    // Health codes
    HEALTH_CHECK_SUCCESS: '200500',

    // Cache codes
    CACHE_OPERATION_SUCCESS: '200600'
}

export const RESPONSE_TYPES = {
    // Success types
    SUCCESS: 'SUCCESS',

    // Auth types
    AUTH_LOGIN: 'AUTH_LOGIN_SUCCESS',
    AUTH_REGISTER: 'AUTH_REGISTER_SUCCESS',
    AUTH_REFRESH: 'AUTH_REFRESH_SUCCESS',
    VERIFY_CODE: 'VERIFY_CODE_SUCCESS',
    AUTH_LOGOUT: 'AUTH_LOGOUT_SUCCESS',
    // User types
    USER_FETCH: 'USER_FETCH_SUCCESS',
    USER_UPDATE: 'USER_UPDATE_SUCCESS',
    USER_DELETE: 'USER_DELETE_SUCCESS',

    // Category types (Feature 03)
    CATEGORIES_FETCH: 'CATEGORIES_FETCH_SUCCESS',
    CATEGORY_CREATE: 'CATEGORY_CREATE_SUCCESS',
    CATEGORY_UPDATE: 'CATEGORY_UPDATE_SUCCESS',
    CATEGORY_DELETE: 'CATEGORY_DELETE_SUCCESS',

    // Gig types (Feature 04)
    GIGS_FETCH: 'GIGS_FETCH_SUCCESS',
    GIG_FETCH: 'GIG_FETCH_SUCCESS',
    GIG_CREATE: 'GIG_CREATE_SUCCESS',
    GIG_UPDATE: 'GIG_UPDATE_SUCCESS',
    GIG_PAUSE: 'GIG_PAUSE_SUCCESS',
    GIG_RESUME: 'GIG_RESUME_SUCCESS',
    GIG_DELETE: 'GIG_DELETE_SUCCESS',
    GIG_IMAGE_UPLOAD: 'GIG_IMAGE_UPLOAD_SUCCESS',
    GIG_IMAGE_DELETE: 'GIG_IMAGE_DELETE_SUCCESS',
    GIG_IMAGES_REORDER: 'GIG_IMAGES_REORDER_SUCCESS',

    // Admin Gig Queue types (Feature 05)
    ADMIN_GIG_QUEUE_FETCH: 'ADMIN_GIG_QUEUE_FETCH_SUCCESS',
    ADMIN_GIG_FETCH: 'ADMIN_GIG_FETCH_SUCCESS',
    ADMIN_GIG_APPROVE: 'ADMIN_GIG_APPROVE_SUCCESS',
    ADMIN_GIG_REJECT: 'ADMIN_GIG_REJECT_SUCCESS',

    // Public Gigs + Wishlist types (Feature 06)
    PUBLIC_GIGS_BROWSE: 'PUBLIC_GIGS_BROWSE_SUCCESS',
    PUBLIC_GIG_FETCH: 'PUBLIC_GIG_FETCH_SUCCESS',
    WISHLIST_SAVE: 'WISHLIST_SAVE_SUCCESS',
    WISHLIST_UNSAVE: 'WISHLIST_UNSAVE_SUCCESS',
    WISHLIST_FETCH: 'WISHLIST_FETCH_SUCCESS',

    // Wallet + Withdrawals types (Feature 07 + 13)
    WALLET_FETCH: 'WALLET_FETCH_SUCCESS',
    WALLET_TRANSACTIONS_FETCH: 'WALLET_TRANSACTIONS_FETCH_SUCCESS',
    WALLET_DEPOSIT: 'WALLET_DEPOSIT_SUCCESS',
    WALLET_WITHDRAW: 'WALLET_WITHDRAW_SUCCESS',
    WALLET_BANK_ACCOUNT_UPDATE: 'WALLET_BANK_ACCOUNT_UPDATE_SUCCESS',
    ADMIN_WITHDRAWALS_LIST: 'ADMIN_WITHDRAWALS_LIST_SUCCESS',
    ADMIN_WITHDRAWAL_FETCH: 'ADMIN_WITHDRAWAL_FETCH_SUCCESS',
    ADMIN_WITHDRAWAL_APPROVE: 'ADMIN_WITHDRAWAL_APPROVE_SUCCESS',
    ADMIN_WITHDRAWAL_REJECT: 'ADMIN_WITHDRAWAL_REJECT_SUCCESS',

    // Messaging types (Feature 08)
    MESSAGING_THREAD_CREATE: 'MESSAGING_THREAD_CREATE_SUCCESS',
    MESSAGING_CONVERSATIONS_LIST: 'MESSAGING_CONVERSATIONS_LIST_SUCCESS',
    MESSAGING_MESSAGES_LIST: 'MESSAGING_MESSAGES_LIST_SUCCESS',
    MESSAGING_MESSAGE_SEND: 'MESSAGING_MESSAGE_SEND_SUCCESS',
    MESSAGING_ATTACHMENT_UPLOAD: 'MESSAGING_ATTACHMENT_UPLOAD_SUCCESS',
    MESSAGING_THREAD_READ: 'MESSAGING_THREAD_READ_SUCCESS',
    MESSAGING_UNREAD_COUNT: 'MESSAGING_UNREAD_COUNT_SUCCESS',
    MESSAGING_FILES_LIST: 'MESSAGING_FILES_LIST_SUCCESS',
    MESSAGING_ATTACHMENT_RESOLVE: 'MESSAGING_ATTACHMENT_RESOLVE_SUCCESS',
    MESSAGING_RESPONSE_TIME: 'MESSAGING_RESPONSE_TIME_SUCCESS',

    // Upload types
    UPLOAD_FILE: 'UPLOAD_FILE_SUCCESS',

    // Email types
    EMAIL_SEND: 'EMAIL_SEND_SUCCESS',

    // Health types
    HEALTH_CHECK: 'HEALTH_CHECK_SUCCESS',

    // Cache types
    CACHE_OPERATION: 'CACHE_OPERATION_SUCCESS'
}
